### PR TITLE
add new quotes

### PR DESCRIPTION
**Pull request by fxkk**
I've added a few new quotes, I hope you find those worthy of being included.

Sorry for the second PR, I needed to rewrite the commit.

### CODE REVIEW

**Comment by martijndeb** [comment]
I like it, but they are not sorted by their age. Could you refactor that? I've tried to go album by album. Got stuck at 2007 😂.

So if you could change your contribution in the right sort order, then I'm happy to merge it

**Comment by fxkk** [comment]
No problem, I overlooked that they were ordered by release year.
I found your project while searching for a fun api to practice some go.
Because I really like scooter and their funny shout-outs I had a lot of fun while testing, so thank you for this project ;)
I thought it was the least to give something back and add some content.

Btw. the result is available at https://github.com/fxkk/goscooter, just in case you have need for a scooter go library or a cli :D

**Comment by martijndeb** [comment]
Thanks! I've merged it. The reason you describe is exactly why I created it :). If I get to a capable computer I'll link your repo on the homepage 👌

**Comment by martijndeb** [comment]
@fxkk I've added the link on the frontpage, and made a [little shoutout](https://mastodon.social/@sexybiggetje/108367560383781204) on mastodon.

I was unable to fetch the Bora Bora Bora quote from discogs, it wrote some information so it worked, but it couldn't find the exact track. Changing it from "Bora Bora Bora" to the official "Bora! Bora! Bora!" title didn't work. I think we'll be okay, because it did scrape the album information properly.

**Pull request merged**
